
package com.ws.app;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessorImpl", targetNamespace = "http://app.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessorImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://app.ws.com/", className = "com.ws.app.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://app.ws.com/", className = "com.ws.app.SaveResponse")
    @Action(input = "http://app.ws.com/ProcessorImpl/saveRequest", output = "http://app.ws.com/ProcessorImpl/saveResponse")
    public void save(
            @WebParam(name = "arg0", targetNamespace = "")
                    Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.ws.app.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPerson", targetNamespace = "http://app.ws.com/", className = "com.ws.app.GetAllPerson")
    @ResponseWrapper(localName = "getAllPersonResponse", targetNamespace = "http://app.ws.com/", className = "com.ws.app.GetAllPersonResponse")
    @Action(input = "http://app.ws.com/ProcessorImpl/getAllPersonRequest", output = "http://app.ws.com/ProcessorImpl/getAllPersonResponse")
    public List<Person> getAllPerson();

}
